### ISSUE TITLE
Compilation error after upgrade mysql-native to 1.0.0

### ISSUE THREAD

**Issue by eresid** [buggins/hibernated#49]
`mysql-native 1.0.0: target for configuration "library" is up to date.
ddbc 0.3.2: building configuration "full"...
../../../.dub/packages/ddbc-0.3.2/ddbc/source/ddbc/drivers/mysqlddbc.d(319,15): Error: undefined identifier 'Command'
../../../.dub/packages/ddbc-0.3.2/ddbc/source/ddbc/drivers/mysqlddbc.d(342,23): Error: undefined identifier 'FieldDescription'
../../../.dub/packages/ddbc-0.3.2/ddbc/source/ddbc/drivers/mysqlddbc.d(359,23): Error: undefined identifier 'ParamDescription'
dmd failed with exit code 1.`

**Comment by eresid** [comment]
On first time we can use
"mysql-native": "~>0.1.6"
Instead of
"mysql-native": ">=0.1.6"

**Comment by SingingBush** [comment]
This is no longer relevant. ddbc now supports a newer mysql-native
